package org.una.programmingIII.Assignment_Manager_Client.Dto;

public enum PermissionType {
    CRUD_COURSES,
    VIEW_COURSES,
    CREATE_ASSIGNMENTS,
    SUBMIT_ASSIGNMENTS,
    GRADE_ASSIGNMENTS,
    VIEW_GRADES,
    MANAGE_USERS,
    VIEW_REPORTS,
    EDIT_PROFILE,
    TEACH_CLASSES,
    TAKE_CLASSES,
    GLOBAL_MAINTENANCE,
    EDIT_COURSES,
    REGISTER_STUDENT_COURSES,
}
